version: '3'

services:
  db:
    image: postgres:latest
    container_name: sprint_5_db
    env_file:
      - .docker-env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
#    restart: always
    ports:
      - "5500:5432"
    networks:
      - backend
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  db_test:
    image: postgres:latest
    container_name: db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5050:5432"

#  app:
#    build:
#      context: .
#    container_name: sprint_5_app
#    command: ["./docker/app.sh"]
#    env_file:
#      - .docker-env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    networks:
#      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
